
// let data = new Promise(async (resolve, reject) => {
//     console.log("hii")
//     await setTimeout(() => {
//         console.log("hello")
//         resolve(true)
//     }, 3000);
//     console.log("world")
// })

// let data = new Promise((resolve, reject) => {
//     console.log("hii");
//    setTimeout(() => {
//         console.log("hello");
//         resolve(true);
//     }, 3000);
//     console.log("world");
// });

// data.then((result) => {
//     console.log("Promise resolved with:", result);
// }).catch((error) => {
//     console.error("Promise rejected with:", error);
// });



